### ISSUE TITLE
Duplicated definitions

### ISSUE THREAD

**Issue by jbodart-argenx** [mikmart/vscode-sas#3]
Hello,
for some reason, I'm getting multiple identical definitions when I hover on a macro call.
![image](https://github.com/user-attachments/assets/a025e2ac-7e51-4bb0-aa29-b8ebc6f77e39)
The number of repetitions varies between macros.

I have multiple paths defined in my settings.json:
```
"sas.sasautos": [
  "${workspaceRoot}/macros",
  "C:/Program Files/SASHome/SASFoundation/9.4/core/sasmacro",
  "C:/Program Files/SASHome/SASFoundation/9.4/aacomp/sasmacro",
  "C:/Program Files/SASHome/SASFoundation/9.4/accelmva/sasmacro",
  "C:/Program Files/SASHome/SASFoundation/9.4/dmscore/sasmacro",
  "C:/Program Files/SASHome/SASFoundation/9.4/graph/sasmacro",
  "C:/Program Files/SASHome/SASFoundation/9.4/hps/sasmacro",
  "C:/Program Files/SASHome/SASFoundation/9.4/mlearning/sasmacro",
  "C:/Program Files/SASHome/SASFoundation/9.4/stat/sasmacro",
  "C:/Users/jbodart/lsaf/files/general/biostat/macros/_library",
  "C:/Users/jbodart/lsaf/files/general/biostat/tools/sasunit/saspgm/sasunit"
]
```
I guess some macros may have copies in multiple locations, sometimes in subfolders - is it correct that subfolders of the specified paths are automatically searched for macro definitions ?
Would it be possible to check for multiple definitions and remove exact duplicates from the display ?

Thank you

**Comment by mikmart** [comment]
> I guess some macros may have copies in multiple locations, sometimes in subfolders - is it correct that subfolders of the specified paths are automatically searched for macro definitions?

Yes, multiple copies is what I'd expect to be causing the behaviour you're seeing.

If you try to "jump to definition" for a macro, it should show all the locations where it's defined. If you do that for a macro that shows you multiple definitions in the tooltip, do the locations that come up seem correct to you?

Subfolders should not be automatically searched. I'll have a look to see if that's happening.

> Would it be possible to check for multiple definitions and remove exact duplicates from the display ?

Thanks, that's a good idea! Duplicate definitions in the hover tooltip don't really add anything, so it makes sense to remove them.

**Comment by jbodart-argenx** [comment]
If I click "Go to definition" for a macro that shows multiple definitions in the tooltip, I don't see multiple locations.  It seems it takes me to the main location I expected.

**Comment by mikmart** [comment]
Okay, thanks for checking. In that case I've got some digging to do to figure out what's going on.

**Comment by mikmart** [comment]
@jbodart-argenx this should now be fixed in version 0.2.2 which is on GitHub and released on the marketplace.

Thanks again for reporting this. And do let me know if the fix worked for you; I was able to replicate the behaviour under certain circumstances, but I'm not 100% sure if those are what you were seeing.

**Comment by jbodart-argenx** [comment]
Thanks, will check soon

**Comment by jbodart-argenx** [comment]
The new version seems to work for me, I can't see exact duplicates anymore.
I can still see two distinct definitions for the same macro defined in multiple locations, sometimes with no parentheses and sometimes with empty parentheses and I think this is OK (_I can still suppress the near duplicates by adding empty parentheses where they are not present_), e.g. 

Initially:
```
%macro init_classpath_update;
 ...
%mend:
```
and
```
%macro init_classpath_update();
 ...
%mend;
```
![image](https://github.com/user-attachments/assets/914211f4-4ba2-43b8-9ecf-0e5e1175de19)


After adding empty parentheses where they were not present:
![image](https://github.com/user-attachments/assets/2eb4561b-accd-4204-9be5-0e7c5d36effd)

**Comment by mikmart** [comment]
Thanks! Yeah ideally we'd not repeat functionally equivalent signatures. But that would require the extension to have a much deeper understanding of the language (probably parsing it properly) than it currently does.

**Comment by jbodart-argenx** [comment]
As I wrote earlier, I find that OK, even useful as a way to detect inconsistent definitions and then make them consistent...

**Comment by jbodart-argenx** [comment]
By the way, if there are multiple macro definitions with same name and same or different signatures shown by the tooltip, it's not clear to which one you will jump by clicking 'goto macro definition'.  In such a case, shouldn't it be possible to show all locations in another popup and click on the one you want to access?

**Comment by mikmart** [comment]
Yes, that's exactly what should happen. Do you have an example where it doesn't do that?

**Comment by jbodart-argenx** [comment]
I hadn't realized, but it actually works as described, thanks!
